[project]
name = "moccasin_project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "moccasin>=0.3.6",
    "mox>=0.5.3",
    "pytest>=8.3.4",
    "titanoboa>=0.2.5",
    "vyper>=0.4.0",
]
